import { auth } from '@/auth'
import AppProvider from '@/provider/AppProvider'
import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { Inter } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import { Toaster } from 'sonner'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Musa Gala - Admin Dashboard',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body className={`${inter.className}  antialiased`}>
        <AppProvider>
          <SessionProvider session={session}>{children} </SessionProvider>
        </AppProvider>
        <Toaster richColors position="bottom-right" />
        <NextTopLoader showSpinner={false} color="#1E2A38" />
      </body>
    </html>
  )
}
